version: '3.9'

services:
  heap-dump:
    image: heap-dump:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://heap-postgres:5432/totallyhidden
      SPRING_DATASOURCE_USERNAME: produser
      SPRING_DATASOURCE_PASSWORD: 98yui3hkjrqfaed98y9q0uo
    depends_on:
      - heap-postgres
    networks:
      - heap-net

  heap-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: 98yui3hkjrqfaed98y9q0uo
      POSTGRES_DB: totallyhidden
    ports:
      - "5432:5432"
    networks:
      - heap-net

networks:
  heap-net: {}
